# Generated by Django 6.0.2 on 2026-02-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='maxsulot nomi')),
                ('unit', models.CharField(choices=[('g', 'gramm'), ('kg', 'kilogram'), ('sheet', 'dona'), ('ml', 'milliletr'), ('litr', 'litr')], max_length=255, verbose_name="o'lchov birligi")),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='miqdori')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Masalliq',
                'verbose_name_plural': 'Masalliqlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='meals/')),
                ('status', models.CharField(choices=[('active', 'faol'), ('inactive', 'nofaol')], max_length=21)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('ingredients', models.ManyToManyField(blank=True, to='main.ingredient')),
            ],
            options={
                'verbose_name': 'taom',
                'verbose_name_plural': 'taomalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
