# Generated by Django 6.0.2 on 2026-02-21 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'gramm'), ('kg', 'kilogram'), ('dona', 'dona'), ('ml', 'milliletr'), ('litr', 'litr')], max_length=255, verbose_name="o'lchov birligi"),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meal')),
            ],
        ),
    ]
